### PR TITLE
added a new section and some papers

### PR DESCRIPTION
**Pull request by subhankar01**
CVPR 2021

### CODE REVIEW

**Comment by sbharadwajj** [comment]
Hi! Are there any more papers from CVPR 2021?

**Comment by subhankar01** [comment]
hello! yep, there are! Also many new top tier conference papers which have been recently added to the ZSL literature. I'll add them all

**Comment by sbharadwajj** [comment]
okay that would be great. I will wait for you to update this PR

**Comment by subhankar01** [comment]
yeah I have added them

**Pull request merged**
